workspace:
  base: /app
  path: .

pipeline:
  test:
    image: python:3.5
    environment:
      - PYTHONPATH=/app:$PYTHONPATH
      - CI_BRANCH=${DRONE_COMMIT_BRANCH}
    commands:
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - export CI_BRANCH=${DRONE_COMMIT_BRANCH}
      - export CI_NAME='Drone'
      - export CI_BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - export CI_BUILD_URL=${DRONE_BUILD_LINK}
      - export CI_PULL_REQUEST=${DRONE_PULL_REQUEST}
      - export COVERALLS_REPO_TOKEN=${COVERALLS_TOKEN}
      - coverage run -m unittest discover
      - coverage report -m
      - coveralls
  code-standards:
    image: python:3.5
    environment:
      - PYTHONPATH=/app:$PYTHONPATH
    commands:
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - flake8
      - find . -iname "*.py" | xargs pylint
    when:
      event: [pull_request]
